apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-auth
data:
  .dockerconfigjson: |
    ewogICJhdXRocyI6IHsKICAgICJkb2NrZXItcmVnaXN0cnk6NTAwMCI6IHsKICAgICAgImF1dGgiOi
    AiYUc5dFpYSTZjMmx0Y0hOdmJnPT0iCiAgICB9LAogICAgImRvY2tlci1yZWdpc3RyeS0yOjUwMDAi
    OiB7CiAgICAgICJhdXRoIjogImJXRnlaMlU2YzJsdGNITnZiZz09IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
---
apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: ${TEST_RESOURCE_NAME}
spec:
  imageName: all-registries-from-secret-app
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/variable-base-app.tgz
  disableBuildCache: true
  buildArgs:
    - base=docker-registry:5000/simple-app:latest
  pushTo:
    - docker-registry-2:5000
  registries:
    # The explicit assert here is for second-docker-registry
    # but the push above is to docker-registry (also contained
    # in the dockerconfig.json in the secret). This will only work
    # if all the auth entries from the secret are correctly loaded.
    - server: docker-registry-2:5000
      nonSSL: true
      basicAuth:
        secretName: docker-registry-auth
        secretNamespace: ${TEST_NAMESPACE}
