apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-auth
data:
  .dockerconfigjson: |
    ewogICJhdXRocyI6IHsKICAgICJkb2NrZXItcmVnaXN0cnk6NTAwMCI6IHsKICAgICAgImF1dGgiOi
    AiYUc5dFpYSTZjMmx0Y0hOdmJnPT0iCiAgICB9LAogICAgImRvY2tlci1yZWdpc3RyeS0yOjUwMDAi
    OiB7CiAgICAgICJhdXRoIjogImJXRnlaMlU2YzJsdGNITnZiZz09IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
---
apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: ${TEST_RESOURCE_NAME}
spec:
  imageName: all-registries-from-secret
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/variable-base-app.tgz
  disableBuildCache: true
  buildArgs:
    - base=docker-registry:5000/simple-app:latest
  pushTo:
    - docker-registry-2:5000
  registries:
    # The explicit config below is for docker-registry-2
    # but the base image is from the authenticated host: docker-registry
    # The auth for this registry is also contained in the dockerconfig.json in the docker-registry-auth secret.
    # So, this build will only succeed if all the auth entries from the secret are correctly loaded.
    - server: docker-registry-2:5000
      nonSSL: true
      basicAuth:
        secretName: docker-registry-auth
        secretNamespace: ${TEST_NAMESPACE}
