apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-auth
data:
  .dockerconfigjson: |
    ewogICJhdXRocyI6IHsKICAgICJkb2NrZXItcmVnaXN0cnk6NTAwMCI6IHsKICAgICAgImF1dGgiOi
    AiYUc5dFpYSTZjMmx0Y0hOdmJnPT0iCiAgICB9LAogICAgImRvY2tlci1yZWdpc3RyeS0yOjUwMDAi
    OiB7CiAgICAgICJhdXRoIjogImJXRnlaMlU2YzJsdGNITnZiZz09IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
---
apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: ${TEST_RESOURCE_NAME}
spec:
  imageName: override-implicit-registry-from-secret
  context: https://raw.githubusercontent.com/dominodatalab/forge/master/test/data/variable-base-app.tgz
  disableBuildCache: true
  buildArgs:
    - base=docker-registry:5000/simple-app:latest
  pushTo:
    - docker-registry-2:5000
  registries:
    # The explicit config below is for docker-registry, but auth info for docker-registry-2 is also contained
    # in the docker-registry-auth secret. As a result, auth for docker-registry-2 will be configured with SSL (default).
    # Ergo, this build will only work if the *explicit* config of docker-registry-2 below overrides the implicit config
    # from the first entry, correctly setting NonSSL.
    - server: docker-registry:5000
      nonSSL: false
      basicAuth:
        secretName: docker-registry-auth
        secretNamespace: ${TEST_NAMESPACE}
    - server: docker-registry-2:5000
      nonSSL: true
      basicAuth:
        secretName: docker-registry-auth
        secretNamespace: ${TEST_NAMESPACE}
