apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: test-private-base-image
spec:
  imageName: variable-base-app
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/variable-base-app.tgz
  noCache: true
  buildArgs:
    - base=docker-registry:5000/simple-app:latest
  pushTo:
    - docker-registry-2:5000
  registries:
    - server: docker-registry:5000
      basicAuth:
        username: homer
        password: simpson
    - server: docker-registry-2:5000
      nonSSL: true
      basicAuth:
        username: marge
        password: simpson
