apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: test-tls-with-basic-auth
spec:
  imageName: simple-app
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/simple-app.tgz
  pushTo:
    - docker-registry:5000
  registries:
    - server: docker-registry:5000
      nonSSL: true
      basicAuth:
        username: homer
        password: simpson
