// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/dominodatalab/forge/api/forge/v1alpha1"
	scheme "github.com/dominodatalab/forge/internal/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ContainerImageBuildsGetter has a method to return a ContainerImageBuildInterface.
// A group's client should implement this interface.
type ContainerImageBuildsGetter interface {
	ContainerImageBuilds(namespace string) ContainerImageBuildInterface
}

// ContainerImageBuildInterface has methods to work with ContainerImageBuild resources.
type ContainerImageBuildInterface interface {
	Create(ctx context.Context, containerImageBuild *v1alpha1.ContainerImageBuild, opts v1.CreateOptions) (*v1alpha1.ContainerImageBuild, error)
	Update(ctx context.Context, containerImageBuild *v1alpha1.ContainerImageBuild, opts v1.UpdateOptions) (*v1alpha1.ContainerImageBuild, error)
	UpdateStatus(ctx context.Context, containerImageBuild *v1alpha1.ContainerImageBuild, opts v1.UpdateOptions) (*v1alpha1.ContainerImageBuild, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ContainerImageBuild, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ContainerImageBuildList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ContainerImageBuild, err error)
	ContainerImageBuildExpansion
}

// containerImageBuilds implements ContainerImageBuildInterface
type containerImageBuilds struct {
	client rest.Interface
	ns     string
}

// newContainerImageBuilds returns a ContainerImageBuilds
func newContainerImageBuilds(c *ForgeV1alpha1Client, namespace string) *containerImageBuilds {
	return &containerImageBuilds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the containerImageBuild, and returns the corresponding containerImageBuild object, and an error if there is any.
func (c *containerImageBuilds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ContainerImageBuild, err error) {
	result = &v1alpha1.ContainerImageBuild{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("containerimagebuilds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ContainerImageBuilds that match those selectors.
func (c *containerImageBuilds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ContainerImageBuildList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ContainerImageBuildList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("containerimagebuilds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested containerImageBuilds.
func (c *containerImageBuilds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("containerimagebuilds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a containerImageBuild and creates it.  Returns the server's representation of the containerImageBuild, and an error, if there is any.
func (c *containerImageBuilds) Create(ctx context.Context, containerImageBuild *v1alpha1.ContainerImageBuild, opts v1.CreateOptions) (result *v1alpha1.ContainerImageBuild, err error) {
	result = &v1alpha1.ContainerImageBuild{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("containerimagebuilds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(containerImageBuild).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a containerImageBuild and updates it. Returns the server's representation of the containerImageBuild, and an error, if there is any.
func (c *containerImageBuilds) Update(ctx context.Context, containerImageBuild *v1alpha1.ContainerImageBuild, opts v1.UpdateOptions) (result *v1alpha1.ContainerImageBuild, err error) {
	result = &v1alpha1.ContainerImageBuild{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("containerimagebuilds").
		Name(containerImageBuild.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(containerImageBuild).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *containerImageBuilds) UpdateStatus(ctx context.Context, containerImageBuild *v1alpha1.ContainerImageBuild, opts v1.UpdateOptions) (result *v1alpha1.ContainerImageBuild, err error) {
	result = &v1alpha1.ContainerImageBuild{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("containerimagebuilds").
		Name(containerImageBuild.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(containerImageBuild).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the containerImageBuild and deletes it. Returns an error if one occurs.
func (c *containerImageBuilds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("containerimagebuilds").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *containerImageBuilds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("containerimagebuilds").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched containerImageBuild.
func (c *containerImageBuilds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ContainerImageBuild, err error) {
	result = &v1alpha1.ContainerImageBuild{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("containerimagebuilds").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
