apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: forge
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: forge
    - image: forge-dev
      buildpack:
        builder: "gcr.io/buildpacks/builder"
        runImage: quay.io/domino/forge:dev.latest
        env:
          - GOOGLE_GOLDFLAGS="-X github.com/dominodatalab/forge/cmd.BuildJobImage=forge"
        dependencies:
          paths:
            - api
            - cmd
            - controllers
            - hack
            - internal
            - main.go
            - go.mod
          ignore:
            - config
            - vendor
deploy:
  kustomize:
    paths:
      - config/crd
      - config/controller/overlays/controller-dev
