// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/dominodatalab/forge/api/forge/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeContainerImageBuilds implements ContainerImageBuildInterface
type FakeContainerImageBuilds struct {
	Fake *FakeForgeV1alpha1
	ns   string
}

var containerimagebuildsResource = schema.GroupVersionResource{Group: "forge", Version: "v1alpha1", Resource: "containerimagebuilds"}

var containerimagebuildsKind = schema.GroupVersionKind{Group: "forge", Version: "v1alpha1", Kind: "ContainerImageBuild"}

// Get takes name of the containerImageBuild, and returns the corresponding containerImageBuild object, and an error if there is any.
func (c *FakeContainerImageBuilds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ContainerImageBuild, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(containerimagebuildsResource, c.ns, name), &v1alpha1.ContainerImageBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ContainerImageBuild), err
}

// List takes label and field selectors, and returns the list of ContainerImageBuilds that match those selectors.
func (c *FakeContainerImageBuilds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ContainerImageBuildList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(containerimagebuildsResource, containerimagebuildsKind, c.ns, opts), &v1alpha1.ContainerImageBuildList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ContainerImageBuildList{ListMeta: obj.(*v1alpha1.ContainerImageBuildList).ListMeta}
	for _, item := range obj.(*v1alpha1.ContainerImageBuildList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested containerImageBuilds.
func (c *FakeContainerImageBuilds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(containerimagebuildsResource, c.ns, opts))

}

// Create takes the representation of a containerImageBuild and creates it.  Returns the server's representation of the containerImageBuild, and an error, if there is any.
func (c *FakeContainerImageBuilds) Create(ctx context.Context, containerImageBuild *v1alpha1.ContainerImageBuild, opts v1.CreateOptions) (result *v1alpha1.ContainerImageBuild, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(containerimagebuildsResource, c.ns, containerImageBuild), &v1alpha1.ContainerImageBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ContainerImageBuild), err
}

// Update takes the representation of a containerImageBuild and updates it. Returns the server's representation of the containerImageBuild, and an error, if there is any.
func (c *FakeContainerImageBuilds) Update(ctx context.Context, containerImageBuild *v1alpha1.ContainerImageBuild, opts v1.UpdateOptions) (result *v1alpha1.ContainerImageBuild, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(containerimagebuildsResource, c.ns, containerImageBuild), &v1alpha1.ContainerImageBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ContainerImageBuild), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeContainerImageBuilds) UpdateStatus(ctx context.Context, containerImageBuild *v1alpha1.ContainerImageBuild, opts v1.UpdateOptions) (*v1alpha1.ContainerImageBuild, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(containerimagebuildsResource, "status", c.ns, containerImageBuild), &v1alpha1.ContainerImageBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ContainerImageBuild), err
}

// Delete takes name of the containerImageBuild and deletes it. Returns an error if one occurs.
func (c *FakeContainerImageBuilds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(containerimagebuildsResource, c.ns, name), &v1alpha1.ContainerImageBuild{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeContainerImageBuilds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(containerimagebuildsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ContainerImageBuildList{})
	return err
}

// Patch applies the patch and returns the patched containerImageBuild.
func (c *FakeContainerImageBuilds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ContainerImageBuild, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(containerimagebuildsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ContainerImageBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ContainerImageBuild), err
}
