// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/dominodatalab/forge/internal/clientset/typed/forge/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeForgeV1alpha1 struct {
	*testing.Fake
}

func (c *FakeForgeV1alpha1) ContainerImageBuilds(namespace string) v1alpha1.ContainerImageBuildInterface {
	return &FakeContainerImageBuilds{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeForgeV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
