version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    environment:
      KUBEBUILDER_VERSION: 2.2.0
    steps:
      - checkout
      - run:
          name: Install Kubebuilder
          command: |
            os=$(go env GOOS)
            arch=$(go env GOARCH)
            curl -L https://go.kubebuilder.io/dl/${KUBEBUILDER_VERSION}/${os}/${arch} | tar -xz -C /tmp/
            sudo mv /tmp/kubebuilder_${KUBEBUILDER_VERSION}_${os}_${arch} /usr/local/kubebuilder
            echo 'export PATH=$PATH:/usr/local/kubebuilder/bin' >> $BASH_ENV
      - restore_cache:
          keys:
            - go-modules-v1-{{ checksum "go.sum" }}
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: make docker-build
      - save_cache:
          key: go-modules-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  e2e_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Kubernetes
          command: curl -sfL https://get.k3s.io | sh -

workflows:
  version: 2
  main:
    jobs:
      - build
      - e2e_test:
          requires:
            - build

#      - publish
