version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    environment:
      KUBEBUILDER_VERSION: 2.2.0
    steps:
      - checkout
      - run:
          name: Install kubebuilder
          command: |
            os=$(go env GOOS)
            arch=$(go env GOARCH)
            curl -L https://go.kubebuilder.io/dl/${KUBEBUILDER_VERSION}/${os}/${arch} | tar -xz -C /tmp/
            sudo mv /tmp/kubebuilder_${KUBEBUILDER_VERSION}_${os}_${arch} /usr/local/kubebuilder
            echo 'export PATH=$PATH:/usr/local/kubebuilder/bin' >> $BASH_ENV
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Install go modules
          command: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - setup_remote_docker
      - run:
          name: Build docker image
          command: make docker-build
