# permissions to do edit containerimagebuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerimagebuild-editor-role
rules:
- apiGroups:
  - forge.dominodatalab.com
  resources:
  - containerimagebuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - forge.dominodatalab.com
  resources:
  - containerimagebuilds/status
  verbs:
  - get
  - patch
  - update
