# permissions to do viewer containerimagebuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerimagebuild-viewer-role
rules:
- apiGroups:
  - forge.dominodatalab.com
  resources:
  - containerimagebuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - forge.dominodatalab.com
  resources:
  - containerimagebuilds/status
  verbs:
  - get
