apiVersion: v1
kind: Secret
metadata:
 name: docker-registry-auth
data:
 .dockerconfigjson: |
    ewogICJhdXRocyI6IHsKICAgICJkb2NrZXItcmVnaXN0cnk6NTAwMCI6IHsKICAgICAgImF1dGgi
    OiAiYldGeVoyVTZjMmx0Y0hOdmJnPT0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
