apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: example-build
  namespace: default
spec:
  # tag is optional (e.g. multi-stage-app:v1.0.0)
  imageName: multi-stage-app

  # remote context can either be a .tar or .tgz file
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/multi-stage-app.tgz

  # disable the cache if necessary
  noCache: false

  # metadata attached to image during build
  labels:
    dominodatalab.com/build-id: abc123
    dominodatalab.com/environment-id: dev

  # image build args
  buildArgs:
    - port=5000

  # do not push image if greater than 50MB
  imageSizeLimit: 52428800

  # push image to one or more registries after build
  pushTo:
    - my-docker-registry:5000

  # configure auth/https for one or more registries (used to pull/push/resolve images)
  registries:
    # inline basic auth credentials
    - server: quay.io
      basicAuth:
          username: foo
          password: bar
    # secret with dockerconfigjson auth credentials
    - server: docker.io
      basicAuth:
        secretName: docker-io-auth
        secretNamespace: your-ns
    # registry w/o tls encryption and basic auth
    - server: my-docker-registry:5000
      noSSL: true
