apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: example-build
spec:
  # tag is optional (e.g. multi-stage-app:v1.0.0)
  imageName: multi-stage-app

  # remote context can either be a .tar or .tgz file
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/multi-stage-app.tgz

  # disable the cache if necessary
  noCache: false

  # metadata attached to image during build
  labels:
    dominodatalab.com/build-id: abc123
    dominodatalab.com/environment-id: dev

  # image build args
  buildArgs:
    - port=5000

  # do not push image if greater than 50MB
  imageSizeLimit: 52428800

  # push details for one or more registries
  registries:
    - # push image here after build
      url: my-docker-registry:5000

      # push to a plain HTTP registry
      insecure: false

      # push to a registry with native basic auth ("Inline","Secret")
      basicAuth: Secret

      # secret containing dockerconfigjson credentials to registry
      secretName: my-docker-config-json-secret

      # namespace where secret resides
      secretNamespace: my-ns

      # inline basic auth username
      #username: docker-push-user

      # inline basic auth password
      #password: $0$3cr3t
