apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: containerimagebuild-sample
spec:
  build:
    pushRegistry: docker-registry:5000
    imageName: domino/env-build
    commands:
      - FROM python:3.7
      - RUN pip install awscli
      - RUN echo 'all done'
      - CMD ["/bin/bash"]
