// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageBuild) DeepCopyInto(out *ContainerImageBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageBuild.
func (in *ContainerImageBuild) DeepCopy() *ContainerImageBuild {
	if in == nil {
		return nil
	}
	out := new(ContainerImageBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerImageBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageBuildList) DeepCopyInto(out *ContainerImageBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerImageBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageBuildList.
func (in *ContainerImageBuildList) DeepCopy() *ContainerImageBuildList {
	if in == nil {
		return nil
	}
	out := new(ContainerImageBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerImageBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageBuildSpec) DeepCopyInto(out *ContainerImageBuildSpec) {
	*out = *in
	if in.BuildArgs != nil {
		in, out := &in.BuildArgs, &out.BuildArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageBuildSpec.
func (in *ContainerImageBuildSpec) DeepCopy() *ContainerImageBuildSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerImageBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageBuildStatus) DeepCopyInto(out *ContainerImageBuildStatus) {
	*out = *in
	if in.BuildStartedAt != nil {
		in, out := &in.BuildStartedAt, &out.BuildStartedAt
		*out = (*in).DeepCopy()
	}
	if in.BuildCompletedAt != nil {
		in, out := &in.BuildCompletedAt, &out.BuildCompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageBuildStatus.
func (in *ContainerImageBuildStatus) DeepCopy() *ContainerImageBuildStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerImageBuildStatus)
	in.DeepCopyInto(out)
	return out
}
