apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-controller
  labels:
    app.kubernetes.io/name: forge
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: forge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forge
    spec:
      serviceAccountName: forge
      initContainers:
        - name: apply-crd
          image: quay.io/domino/forge:latest
          imagePullPolicy: IfNotPresent
          args:
            - crd-apply
      terminationGracePeriodSeconds: 10
      containers:
        - name: controller
          image: quay.io/domino/forge:latest
          imagePullPolicy: IfNotPresent
          args:
            - --namespace
            - $(WATCH_NAMESPACE)
            - --build-job-custom-ca
            - docker-registry-tls
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 1
              memory: 20Mi
      terminationGracePeriodSeconds: 10
