apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/domino/forge
  newName: quay.io/domino/forge
  newTag: latest
namespace: default
resources:
- serviceaccount.yaml
- rbac.yaml
- deployment.yaml
