apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: test-pull-acr
spec:
  imageName: variable-base-app
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/variable-base-app.tgz
  disableBuildCache: true
  buildArgs:
    - base=ACR/simple-app:latest
  pushTo:
    - ACR
  registries:
    - server: ACR
      dynamicCloudCredentials: true
