apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: test-push-acr
spec:
  imageName: simple-app
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/simple-app.tgz
  pushTo:
    - ACR
  registries:
    - server: ACR
      dynamicCloudCredentials: true
