apiVersion: v1
kind: Secret
metadata:
 name: docker-registry-auth
data:
  # base64 encoded config for a single registry at docker-registry:5000
  # with username:password marge:simpson - matching the registry configured locally using helm.
 .dockerconfigjson: |
    ewogICJhdXRocyI6IHsKICAgICJkb2NrZXItcmVnaXN0cnk6NTAwMCI6IHsKICAgICAgImF1dGgi
    OiAiYldGeVoyVTZjMmx0Y0hOdmJnPT0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
