apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-controller
  labels:
    app.kubernetes.io/name: forge
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: forge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forge
      annotations:
        logKey: forge
    spec:
      serviceAccountName: forge
      volumes:
        - name: ca-tls
          secret:
            secretName: docker-registry-tls
        - name: ssl-certs
          emptyDir: {}
      initContainers:
        - name: init-ca
          image: debian:latest
          command:
            - sh
            - -c
            - |
              set -ex
              apt update
              apt install -y ca-certificates
              cp /tmp/forge/ca-tls/ca.crt /usr/local/share/ca-certificates/custom.crt
              update-ca-certificates
          env:
            - name: CERT_DIR
              value: /tmp/forge/ca-tls
          volumeMounts:
            - name: ca-tls
              mountPath: /tmp/forge/ca-tls
            - name: ssl-certs
              mountPath: /etc/ssl/certs
      containers:
        - name: controller
          image: quay.io/domino/forge:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MESSAGE_BROKEN
              value: amqp
            - name: AMQP_URI
              value: amqp://user:password@rabbitmq
            - name: AMQP_QUEUE
              value: containerimagebuilds.status-update
          # env:
          #   - name: IMG_RUNNING_TESTS
          #     value: "1"
          resources:
            requests:
              cpu: 1
              memory: 20Mi
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
          securityContext:
            privileged: true # TODO: figure out why this is required for k3s testing in CircleCI and then remove
      terminationGracePeriodSeconds: 10
