apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-controller
  labels:
    app.kubernetes.io/name: forge
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: forge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forge
    spec:
      serviceAccountName: forge
      containers:
        - name: controller
          image: forge:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
