apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: forge-controller
rules:
  - apiGroups:
      - forge.dominodatalab.com
    resources:
      - containerimagebuilds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - forge.dominodatalab.com
    resources:
      - containerimagebuilds/status
    verbs:
      - get
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forge-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forge-controller
subjects:
  - kind: ServiceAccount
    name: forge
