apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: all-registries-from-secret-build
  namespace: default
spec:
  imageName: all-registries-from-secret
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/multi-stage-app.tgz
  pushTo:
    - docker-registry:5000
  registries:
    # The explicit config below is for second-docker-registry
    # but the push target is for the authenticated host: docker-registry
    # The auth for this registry is also contained in the dockerconfig.json in the docker-registry-auth secret.
    # So, this build will only succeed if all the auth entries from the secret are correctly loaded.
    - server: second-docker-registry:5000
      nonSSL: true
      basicAuth:
        secretName: docker-registry-auth
        secretNamespace: default
