apiVersion: forge.dominodatalab.com/v1alpha1
kind: ContainerImageBuild
metadata:
  name: two-registries-from-secret-build
  namespace: default
spec:
  imageName: two-registries
  context: https://forge-builder-test.s3-us-west-2.amazonaws.com/multi-stage-app.tgz
  pushTo:
    - docker-registry:5000
  registries:
    # The explicit assert here is for second-docker-registry
    # but the push above is to docker-registry (also contained
    # in the dockerconfig.json in the secret). This will only work
    # if all the auth entries from the secret are correctly loaded.
    - server: second-docker-registry:5000
      nonSSL: true
      basicAuth:
        secretName: docker-registry-auth
        secretNamespace: default
