apiVersion: v1
kind: Secret
metadata:
 name: docker-registry-auth
data:
 .dockerconfigjson: |
   ewogICJhdXRocyI6IHsKICAgICJkb2NrZXItcmVnaXN0cnk6NTAwMCI6IHsKICAgICAgImF1dGgiOi
   AiYUc5dFpYSTZjMmx0Y0hOdmJnPT0iCiAgICB9LAogICAgImRvY2tlci1yZWdpc3RyeS0yOjUwMDAi
   OiB7CiAgICAgICJhdXRoIjogImJXRnlaMlU2YzJsdGNITnZiZz09IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
