apiVersion: v1
kind: Secret
metadata:
 name: docker-registry-auth
data:
 .dockerconfigjson: |
   ewogICJhdXRocyI6IHsKICAgICJkb2NrZXItcmVnaXN0cnk6NTAwMCI6IHsKICAgICAgImF1dGgi
   OiAiYUc5dFpYSTZjMmx0Y0hOdmJnbz0iCiAgICB9LAogICAgImRvY2tlci1yZWdpc3RyeS0yOjUw
   MDAiOiB7CiAgICAgICJhdXRoIjogImJXRnlaMlU2YzJsdGNITnZiZ289IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
